School/Controllers/CoursesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;

namespace School.Controllers
{
    public class CoursesController : Controller
    {
        private readonly SchoolContext _context;

        public CoursesController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            var schoolContext = _context.Course.Include(c => c.Department);
            return View(await schoolContext.ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.CourseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            PopulateDepartmentsDropDownList();
            return View();
        }
        public IActionResult _Create()
        {
            PopulateDepartmentsDropDownList();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> _Create(int[] CourseID, string[] Title, int[] Credits, int[] DepartmentID)
        {
            List<Course> courses = new List<Course>();
            for (int i = 0; i < CourseID.Length; i++)
            {
                Course course = new Course();
                course.CourseID = CourseID[i];
                course.Title = Title[i];
                course.Credits = Credits[i];
                course.DepartmentID = DepartmentID[i];
                course.Department = _context.Department.SingleOrDefault(x => x.DepartmentID == DepartmentID[i]);
                courses.Add(course);
            }

            if (ModelState.IsValid)
            {
                _context.Course.AddRange(courses);
                await _context.SaveChangesAsync();
                return View("_Index", courses);
            }
            return null;
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseID,Title,Credits,DepartmentID")] Course course)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(course);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " +
            "Try again, and if the problem persists, " +
            "see your system administrator.");
            }
            PopulateDepartmentsDropDownList(course.DepartmentID);
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            PopulateDepartmentsDropDownList(course.DepartmentID);
            return View("_Edit", course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var updateToCourse = await _context.Course
                .Include(x=>x.Department)
                .SingleOrDefaultAsync(i => i.CourseID == id);
            if (await TryUpdateModelAsync<Course>(updateToCourse, "",
                c => c.Title, c => c.Credits, c => c.DepartmentID))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    //return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. " +
                "Try again, and if the problem persists, " +
                "see your system administrator.");
                }
                IList<Course> courses = new List<Course>();
                courses.Add(updateToCourse);
                return View("_Index", courses);
                //return RedirectToAction("Index");
            }
            PopulateDepartmentsDropDownList(updateToCourse.DepartmentID);
            return View(updateToCourse);
        }
        private void PopulateDepartmentsDropDownList(object selectedDepartment = null)
        {
            var departmentsQuery = from d in _context.Department
                                   orderby d.Name
                                   select d;
            ViewBag.DepartmentID = new SelectList(departmentsQuery.AsNoTracking(), "DepartmentID", "Name", selectedDepartment);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var course = await _context.Course.SingleOrDefaultAsync(m => m.CourseID == id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return Json(true);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.SingleOrDefaultAsync(m => m.CourseID == id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.CourseID == id);
        }
    }
}

School/Controllers/SPAin1PlatformController.cs
using Microsoft.AspNetCore.Mvc;

namespace School.Controllers
{
    public class SPAin1PlatformController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

School/Controllers/StudentsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;
using School.Models.SchoolViewModel;

namespace School.Controllers
{
    public class StudentsController : Controller
    {
        private readonly SchoolContext _context;
         
        public StudentsController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index(string sortOrder, string searchString, int? pageNumber, string currentFilter)
        {
            ViewData["NameSort"] = String.IsNullOrEmpty(sortOrder) ? "nameDesc" : "";
            ViewData["DateSort"] = sortOrder == "Date" ? "dateDesc" : "Date";
            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentSort"] = sortOrder;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }


            var students = from s in _context.Student
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.FirstMidName.StartsWith(searchString) ||
                s.LastName.StartsWith(searchString));
            }

            switch (sortOrder)
            {
                case "nameDesc":
                    students = _context.Student.OrderByDescending(i => i.LastName);
                    break;
                case "dateDesc":
                    students = _context.Student.OrderByDescending(i => i.EnrollmentDate);
                    break;
                case "Date":
                    students = _context.Student.OrderBy(i => i.EnrollmentDate);
                    break;
                default:
                    students = _context.Student.OrderBy(i => i.LastName);
                    break;
            }
            int pageSize = 4;
            return View(await PaginatedList<Student>.CreateAsync(students.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .Include(i => i.Enrollments)
                    .ThenInclude(i => i.Course)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LastName,FirstMidName,EnrollmentDate")] Student student)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(student);
                    await _context.SaveChangesAsync();
                    return PartialView("_Index", student);
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " +
            "Try again, and if the problem persists, " +
            "see your system administrator.");
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int id, [Bind("ID,EnrollmentDate,FirstMidName,LastName")] Student student)
        {
            if (id != student.ID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                    return PartialView("_Index", student);
                }
                catch (DbUpdateException /* ex */)
                {
                    //Log the error (uncomment ex variable name and write a log.)
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (student == null)
            {
                return NotFound();
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again, and if the problem persists " +
                    "see your system administrator.";
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            var student = await _context.Student.FindAsync(id);
            _context.Student.Remove(student);
            await _context.SaveChangesAsync();
            return Json(true);
        }

        public async Task<IActionResult> _AddCourseModal(int studentID)
        {
            ViewBag.StudentID = studentID;
            var courses = await _context.Course.Where(x => x.Enrollments.Any(y => y.StudentID == studentID) == false).ToListAsync();
            return PartialView(courses);
        }
        public async Task<IActionResult> addEnrollment(Enrollment enrollment)//int StudentID,int CourseID)
        {
            enrollment.Course = await _context.Course.SingleAsync(x => x.CourseID == enrollment.CourseID);
            _context.Enrollment.Add(enrollment);
            await _context.SaveChangesAsync();
            return PartialView("_Details", enrollment);
        }
        public async Task<IActionResult> deleteEnrollment(int enrollmentID)
        {
            var enrollment = await _context.Enrollment.SingleAsync(x => x.EnrollmentID == enrollmentID);
            _context.Enrollment.Remove(enrollment);
            return Json(await _context.SaveChangesAsync() > 0);
        }

        private bool StudentExists(int id)
        {
            return _context.Student.Any(e => e.ID == id);
        }
    }
}

School/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/School.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sideNav.css"  />
    <script src="https://kit.fontawesome.com/3dc5fff7a5.js" crossorigin="anonymous"></script>
</head>
<body>
    @*<header>
       
    </header>*@
    @*<div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>*@
    @*<div id="wrapper" ng-cloak>

        @{ await Html.RenderPartialAsync("_Navigation");}
        <div id="page-wrapper">
            <div class="container-fluid">

                <div id="toufiqElahy">@RenderBody()</div>
            </div>
        </div>
    </div>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <div id="wrapper" ng-cloak>

        @{ await Html.RenderPartialAsync("_Navigation");}
        <div id="page-wrapper">
            <div class="container-fluid">

                <div id="toufiqElahy">@RenderBody()</div>
            </div>
        </div>
    </div>

    <!-- Global Modal -->
    <div id="globalModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content" id="globalModalContent">
                .
                @*<div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Modal Header</h4>
                    </div>
                    <div class="modal-body">
                        <p>Some text in the modal.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>*@
            </div>

        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - School - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <link rel="stylesheet" href="~/SPA/toufiqElahySPA.css" />
    <script src="~/SPA/toufiqElahySPA.js"></script>

    <script>
        $(function(){
            $("#toufiqElahy").toufiqSPA();
        })
    </script>

</body>
</html>

School/Views/Shared/_Navigation.cshtml
@*<header class="container-fluid bg-dark">
*@
<nav class="navbar navbar-expand-sm navbar-toggleable-sm  navbar-dark bg-dark box-shadow mb-3 position-fixed w-100">
    <div class="container-fluid">
        <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">School Management</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                @*<li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>*@
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Students" asp-action="Index">Student</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Instructors" asp-action="Index">Instructor</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Courses" asp-action="Index">Course</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Departments" asp-action="Index">Department</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
            </ul>
        </div>
    </div>

     <div class="container pull-left">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-left">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                </div>
            <div class="navbar-collapse collapse navbar-collapse-left">
                <ul class="side-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li>
                        @*<a href="#demo" data-toggle="collapse">Magical Interface <span class="glyphicon glyphicon-plus"></span></a>

                            <button id="demo" href="@Url.Action("Index", "SPAin1Platform")" class="collapse btn-primary pull-right btn-lg">
                            SPA in 1 Platform
                            </button>*@

                         <input type="button" class="btn btn-primary" value="Magical Interface" onclick="window.location= '@Url.Action( "Index", "SPAin1Platform")'" />
                    </li>
                </ul>
            </div>
        </div>
</nav>
@*</header>
*@